### ISSUE TITLE
Composer Require doesn't work if min-stability is set to 'stable'

### ISSUE THREAD

**Issue by smazurov** [JoshuaEstes/FeatureToggle#8]
Because `doctrine/common:2.5` is in an alias to dev version, `composer require` fails as it can't load the dependancy. I see you've committed some fixes to this into master, but since `0.2.0` is latest stable release, `composer require` still fails. Perhaps cut new version that fixes the dependency stability? 

On a somewhat unrelated note, in my opinion, using readthedocs instead of plain readme is overly complicated for such a simple package. 

Otherwise thank you for putting together a simple and well tested reusable component.

**Comment by JoshuaEstes** [comment]
I went ahead and made a new release that should solve some of these issues, for a full diff see https://github.com/JoshuaEstes/FeatureToggle/compare/0.2.0...0.3.0 Let me know if it doesn't work and when I get some time I'll look into this a little more.

Once I get some more time I would like to add the information into the README.md file with basic info and more info at read the docs. I agree that it's a little overkill =p

Thanks for the feedback. I'm hoping I can put out a better product in the future. Any suggestions are welcomed.

**Comment by smazurov** [comment]
I think whats missing is `$context` which will determine if feature is turned on or off, also there should be some force on/off options for features. 

I want to create a container, add context (user, tenant), add a bunch of features, then make determination in the code whether or not they're turned on or off. I can sort of use a toggle for this, but because you're using `OptionsResolver` from symphony it limits on what I can do.

**Comment by JoshuaEstes** [comment]
Well, I have been wanting to get rid of some of the extra stuff in the library and rename some things. This might be a good time to do this. Thank you.

**Comment by smazurov** [comment]
Cool! Closing this since you resolved the original issue. Thank you.
